import Head from 'next/head'
import Creator from "@/components/Creator";
import {Provider} from "react-redux";
import {store} from "@/store/store";

export default function Home() {
    return (
        <>
            <Head>
                <title>Website Creator</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Provider store={store}>
                    <Creator/>
                </Provider>
            </main>
        </>
    )
}
